const authConstants = {
  USERS_LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  USERS_LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  USERS_LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILURE: "GET_USER_INFO_FAILURE",
};

export { authConstants };
