const taskConstants = {
  ADD_NEW_TASK_REQUEST: "ADD_NEW_TASK_REQUEST",
  ADD_NEW_TASK_FAILURE: "ADD_NEW_TASK_FAILURE",
  ADD_NEW_TASK_SUCCESS: "ADD_NEW_TASK_SUCCESS",

  UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",

  GET_ALL_TASK_REQUEST: "GET_ALL_TASK_REQUEST",
  GET_ALL_TASK_FAILURE: "GET_ALL_TASK_FAILURE",
  GET_ALL_TASK_SUCCESS: "GET_ALL_TASK_SUCCESS",
};

export { taskConstants };
